# Generated by Django 5.0.6 on 2024-06-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_resource_planning_management', '0003_productopedidos_cantidad_tipomedidaproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoMedidaProducto',
        ),
    ]
