# Generated by Django 5.0.6 on 2024-06-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_resource_planning_management', '0004_delete_tipomedidaproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoPedidos',
        ),
    ]
